services:
  - type: web
    name: nsut-attendance-bot
    env: python
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt && python -m playwright install chromium
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 180
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
      - key: PYTHON_VERSION
        value: 3.10.0
